// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/29/2025, 9:07:51 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/plugins/**/*.{js,ts,mjs}","/workspace/composables/**/*.{js,ts,mjs}","/workspace/utils/**/*.{js,ts,mjs}","/workspace/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspace/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspace/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;